name: Deploy to Firebase Hosting on Pull
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FOOTBALL_TOURNAMENT_PLANNER }}'
          channelId: ${{ github.event.number }}
          projectId: football-tournament-planner
